### PR TITLE
add read all permissions to diff commenter

### PR DESCRIPTION
**Pull request by zkamvar**
We were having trouble commenting the diff in #103 and have no clue why it's not working. Maybe this will fix it?

### CODE REVIEW

**Review by annakrystalli — APPROVED** [review]
Sure why not!

**Comment by annakrystalli** [comment]
Does this need to be in #103 to work for it?

**Comment by zkamvar** [comment]
No, it just needs to be in main

**Comment by zkamvar** [comment]
No guarantee that it will work since it appeared to work before :/

**Comment by zkamvar** [comment]
okay no it doesn't work -_-

**Comment by annakrystalli** [comment]
# 😭

**Pull request merged**
